### PR TITLE
Responsive-ui-04072018 [WIP]

### PR DESCRIPTION
**Pull request by probuse**
This fixes the issue with the site not being responsive
@abhishek71994  @Gitty73 what do you think of this?

### CODE REVIEW

**Comment by abhishek71994** [comment]
I think the code looks very well.. I will have to check it out in my PC to give a thorough review. Great work @probuse I'll get back by tomorrow.

**Comment by probuse** [comment]
:+1:  @abhishek71994 
Waiting for the thorough review

**Comment by probuse** [comment]
@abhishek71994 @Gitty73  please review and give feedback on the UI.
Next we are implementing the logic.

**Comment by abhishek71994** [comment]
Looks good to me

**Comment by abhishek71994** [comment]
I deleted this branch as the feature looked complete. I hope that's okay.

**Comment by probuse** [comment]
Hello
It is alright.

**Pull request merged**
